.\" Hey, EMACS: -*- nroff -*-
.TH UBUNTU-KYLIN-SOFTWARE-CENTER-DAEMON 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ubuntu-kylin-software-center-daemon \- ubuntu-kylin-software-center back-up services
.SH SYNOPSIS
.B ubuntu-kylin-software-center-daemon
.SH DESCRIPTION
.B ubuntu-kylin-software-center-daemon
It is ubuntu-kylin-software-center back-up services.
.PP
.SH SEE ALSO
.BR ubuntu-kylin-software-center-daemon (1),
.br
.SH AUTHOR
ubuntu-kylin-software-center was written by wukaige <wukaige@kylinos.cn>.
.PP
This manual page was written by wukaige <wukaige@kylinos.cn>.

