.\" Hey, EMACS: -*- nroff -*-
.TH ubuntu-kylin-software-center-daemon 1 "19 AUG 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ubuntu-kylin-software-center-daemon \- launch ubuntu-kylin-software-center-daemon frontends
.SH SYNOPSIS
.B ubuntu-kylin-software-center-daemon
.SH DESCRIPTION
.B ubuntu-kylin-software-center-daemon
It is used to launch backends.Need to use root privilege.
.PP
.SH SEE ALSO
.BR ubuntu-kylin-software-center-daemon (1),
.br
.SH AUTHOR
ubuntu-kylin-software-center-daemon was written by kylin.
.PP
