.\" Hey, EMACS: -*- nroff -*-
.TH ubuntu-kylin-software-center 1 "19 AUG 2013"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ubuntu-kylin-software-center \- launch ubuntu-kylin-software-center frontends
.SH SYNOPSIS
.B ubuntu-kylin-software-center
.SH DESCRIPTION
.B ubuntu-kylin-software-center
It is used to launch frontends.
.PP
.SH SEE ALSO
.BR ubuntu-kylin-software-center (1),
.br
.SH AUTHOR
ubuntu-kylin-software-center was written by kylin.
.PP

