.\" Hey, EMACS: -*- nroff -*-
.TH KYLIN-SOFTWARE-CENTER 1 "22 DEC 2017"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
ubuntu-kylin-software-center \- launch ubuntu-kylin-software-center.py 
.SH SYNOPSIS
.B ubuntu-kylin-software-center
.SH DESCRIPTION
.B ubuntu-kylin-software-center
It is shell script launch ubuntu-kylin-software-center.py
.PP
.SH SEE ALSO
.BR ubuntu-kylin-software-center.py (1),
.br
.SH AUTHOR
ubuntu-kylin-software-center was written by wukaige <wukaige@kylinos.cn>.
.PP
ubuntu-kylin-software-center was written by wukaige <wukaige@kylinos.cn>.

