#!/bin/sh
if [ $# = 0 ]; then
	echo "normal start"
	cd /usr/share/ubuntu-kylin-software-center
	python ubuntu-kylin-software-center.py
else
	if [ $1 = "-quiet" ]; then
		echo "quiet start"
		cd /usr/share/ubuntu-kylin-software-center
		python ubuntu-kylin-software-center.py -quiet
	else
		cd /usr/share/ubuntu-kylin-software-center
		python ubuntu-kylin-software-center.py $1
	fi
fi
