#!/bin/sh

if [ "$1" = "configure" ] ; then
    PKILL=$(which pkill)
    PGREP=$(which pgrep)
    FLAG=`$PGREP -f ubuntu-kylin-software-center-daemon`
    if [ $FLAG > 1 ] ; then
        $PKILL -f -9 ubuntu-kylin-software-center-daemon
    fi
fi

#DEBHELPER#
