# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Sep  9 15:22:04 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(980, 608)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.navWidget = QtGui.QWidget(self.centralwidget)
        self.navWidget.setGeometry(QtCore.QRect(0, 0, 80, 608))
        self.navWidget.setObjectName(_fromUtf8("navWidget"))
        self.logoImg = QtGui.QLabel(self.navWidget)
        self.logoImg.setGeometry(QtCore.QRect(0, 0, 80, 80))
        self.logoImg.setText(_fromUtf8(""))
        self.logoImg.setObjectName(_fromUtf8("logoImg"))
        self.btnHomepage = QtGui.QPushButton(self.navWidget)
        self.btnHomepage.setGeometry(QtCore.QRect(0, 80, 80, 88))
        self.btnHomepage.setText(_fromUtf8(""))
        self.btnHomepage.setObjectName(_fromUtf8("btnHomepage"))
        self.btnUp = QtGui.QPushButton(self.navWidget)
        self.btnUp.setGeometry(QtCore.QRect(0, 256, 80, 88))
        self.btnUp.setText(_fromUtf8(""))
        self.btnUp.setObjectName(_fromUtf8("btnUp"))
        self.btnUn = QtGui.QPushButton(self.navWidget)
        self.btnUn.setGeometry(QtCore.QRect(0, 344, 80, 88))
        self.btnUn.setText(_fromUtf8(""))
        self.btnUn.setObjectName(_fromUtf8("btnUn"))
        self.btnWin = QtGui.QPushButton(self.navWidget)
        self.btnWin.setGeometry(QtCore.QRect(0, 432, 80, 88))
        self.btnWin.setText(_fromUtf8(""))
        self.btnWin.setObjectName(_fromUtf8("btnWin"))
        self.btnTask = QtGui.QPushButton(self.navWidget)
        self.btnTask.setGeometry(QtCore.QRect(0, 520, 80, 88))
        self.btnTask.setText(_fromUtf8(""))
        self.btnTask.setObjectName(_fromUtf8("btnTask"))
        self.btnAll = QtGui.QPushButton(self.navWidget)
        self.btnAll.setGeometry(QtCore.QRect(0, 168, 80, 88))
        self.btnAll.setText(_fromUtf8(""))
        self.btnAll.setObjectName(_fromUtf8("btnAll"))
        self.rightWidget = QtGui.QWidget(self.centralwidget)
        self.rightWidget.setGeometry(QtCore.QRect(80, 0, 900, 608))
        self.rightWidget.setObjectName(_fromUtf8("rightWidget"))
        self.allWidget = QtGui.QWidget(self.rightWidget)
        self.allWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.allWidget.setObjectName(_fromUtf8("allWidget"))
        self.allline = QtGui.QLabel(self.allWidget)
        self.allline.setGeometry(QtCore.QRect(0, 44, 860, 1))
        self.allline.setText(_fromUtf8(""))
        self.allline.setObjectName(_fromUtf8("allline"))
        self.allcount = QtGui.QLabel(self.allWidget)
        self.allcount.setGeometry(QtCore.QRect(772, 20, 50, 15))
        self.allcount.setText(_fromUtf8(""))
        self.allcount.setObjectName(_fromUtf8("allcount"))
        self.alltext1 = QtGui.QLabel(self.allWidget)
        self.alltext1.setGeometry(QtCore.QRect(749, 20, 50, 15))
        self.alltext1.setText(_fromUtf8(""))
        self.alltext1.setObjectName(_fromUtf8("alltext1"))
        self.alltext2 = QtGui.QLabel(self.allWidget)
        self.alltext2.setGeometry(QtCore.QRect(818, 20, 44, 15))
        self.alltext2.setText(_fromUtf8(""))
        self.alltext2.setObjectName(_fromUtf8("alltext2"))
        self.unWidget = QtGui.QWidget(self.rightWidget)
        self.unWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.unWidget.setObjectName(_fromUtf8("unWidget"))
        self.unline = QtGui.QLabel(self.unWidget)
        self.unline.setGeometry(QtCore.QRect(0, 44, 860, 1))
        self.unline.setText(_fromUtf8(""))
        self.unline.setObjectName(_fromUtf8("unline"))
        self.uncount = QtGui.QLabel(self.unWidget)
        self.uncount.setGeometry(QtCore.QRect(777, 20, 50, 15))
        self.uncount.setText(_fromUtf8(""))
        self.uncount.setObjectName(_fromUtf8("uncount"))
        self.untext1 = QtGui.QLabel(self.unWidget)
        self.untext1.setGeometry(QtCore.QRect(750, 20, 50, 15))
        self.untext1.setText(_fromUtf8(""))
        self.untext1.setObjectName(_fromUtf8("untext1"))
        self.untext2 = QtGui.QLabel(self.unWidget)
        self.untext2.setGeometry(QtCore.QRect(818, 20, 44, 15))
        self.untext2.setText(_fromUtf8(""))
        self.untext2.setObjectName(_fromUtf8("untext2"))
        self.homepageWidget = QtGui.QWidget(self.rightWidget)
        self.homepageWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.homepageWidget.setObjectName(_fromUtf8("homepageWidget"))
        self.recommendWidget = QtGui.QWidget(self.homepageWidget)
        self.recommendWidget.setGeometry(QtCore.QRect(0, 298, 640, 268))
        self.recommendWidget.setObjectName(_fromUtf8("recommendWidget"))
        self.rankWidget = QtGui.QWidget(self.homepageWidget)
        self.rankWidget.setGeometry(QtCore.QRect(660, 298, 200, 268))
        self.rankWidget.setObjectName(_fromUtf8("rankWidget"))
        self.rankView = QtGui.QListWidget(self.rankWidget)
        self.rankView.setGeometry(QtCore.QRect(0, 0, 200, 268))
        self.rankView.setObjectName(_fromUtf8("rankView"))
        self.homeMsgWidget = QtGui.QWidget(self.homepageWidget)
        self.homeMsgWidget.setGeometry(QtCore.QRect(0, 0, 860, 44))
        self.homeMsgWidget.setObjectName(_fromUtf8("homeMsgWidget"))
        self.afterLoginWidget = QtGui.QWidget(self.homeMsgWidget)
        self.afterLoginWidget.setGeometry(QtCore.QRect(0, 0, 260, 44))
        self.afterLoginWidget.setObjectName(_fromUtf8("afterLoginWidget"))
        self.userLogoafter = QtGui.QLabel(self.afterLoginWidget)
        self.userLogoafter.setGeometry(QtCore.QRect(0, 14, 16, 16))
        self.userLogoafter.setText(_fromUtf8(""))
        self.userLogoafter.setObjectName(_fromUtf8("userLogoafter"))
        self.welcometext = QtGui.QLabel(self.afterLoginWidget)
        self.welcometext.setGeometry(QtCore.QRect(18, 14, 50, 15))
        self.welcometext.setText(_fromUtf8(""))
        self.welcometext.setObjectName(_fromUtf8("welcometext"))
        self.username = QtGui.QLabel(self.afterLoginWidget)
        self.username.setGeometry(QtCore.QRect(70, 14, 80, 16))
        self.username.setText(_fromUtf8(""))
        self.username.setObjectName(_fromUtf8("username"))
        self.btnLogout = QtGui.QPushButton(self.afterLoginWidget)
        self.btnLogout.setGeometry(QtCore.QRect(160, 14, 45, 15))
        self.btnLogout.setText(_fromUtf8(""))
        self.btnLogout.setObjectName(_fromUtf8("btnLogout"))
        self.beforeLoginWidget = QtGui.QWidget(self.homeMsgWidget)
        self.beforeLoginWidget.setGeometry(QtCore.QRect(0, 0, 260, 44))
        self.beforeLoginWidget.setObjectName(_fromUtf8("beforeLoginWidget"))
        self.userLogo = QtGui.QLabel(self.beforeLoginWidget)
        self.userLogo.setGeometry(QtCore.QRect(0, 14, 16, 16))
        self.userLogo.setText(_fromUtf8(""))
        self.userLogo.setObjectName(_fromUtf8("userLogo"))
        self.btnLogin = QtGui.QPushButton(self.beforeLoginWidget)
        self.btnLogin.setGeometry(QtCore.QRect(18, 14, 50, 15))
        self.btnLogin.setText(_fromUtf8(""))
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.btnReg = QtGui.QPushButton(self.beforeLoginWidget)
        self.btnReg.setGeometry(QtCore.QRect(70, 14, 65, 15))
        self.btnReg.setText(_fromUtf8(""))
        self.btnReg.setObjectName(_fromUtf8("btnReg"))
        self.hometext1 = QtGui.QLabel(self.homepageWidget)
        self.hometext1.setGeometry(QtCore.QRect(0, 275, 60, 15))
        self.hometext1.setText(_fromUtf8(""))
        self.hometext1.setObjectName(_fromUtf8("hometext1"))
        self.hometext2 = QtGui.QLabel(self.homepageWidget)
        self.hometext2.setGeometry(QtCore.QRect(660, 275, 60, 15))
        self.hometext2.setText(_fromUtf8(""))
        self.hometext2.setObjectName(_fromUtf8("hometext2"))
        self.homeline1 = QtGui.QLabel(self.homepageWidget)
        self.homeline1.setGeometry(QtCore.QRect(0, 292, 640, 1))
        self.homeline1.setText(_fromUtf8(""))
        self.homeline1.setObjectName(_fromUtf8("homeline1"))
        self.homeline2 = QtGui.QLabel(self.homepageWidget)
        self.homeline2.setGeometry(QtCore.QRect(660, 292, 200, 1))
        self.homeline2.setText(_fromUtf8(""))
        self.homeline2.setObjectName(_fromUtf8("homeline2"))
        self.searchWidget = QtGui.QWidget(self.rightWidget)
        self.searchWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.searchWidget.setObjectName(_fromUtf8("searchWidget"))
        self.searchline = QtGui.QLabel(self.searchWidget)
        self.searchline.setGeometry(QtCore.QRect(0, 44, 860, 1))
        self.searchline.setText(_fromUtf8(""))
        self.searchline.setObjectName(_fromUtf8("searchline"))
        self.searchcount = QtGui.QLabel(self.searchWidget)
        self.searchcount.setGeometry(QtCore.QRect(777, 20, 50, 15))
        self.searchcount.setText(_fromUtf8(""))
        self.searchcount.setObjectName(_fromUtf8("searchcount"))
        self.searchtext1 = QtGui.QLabel(self.searchWidget)
        self.searchtext1.setGeometry(QtCore.QRect(750, 20, 50, 15))
        self.searchtext1.setText(_fromUtf8(""))
        self.searchtext1.setObjectName(_fromUtf8("searchtext1"))
        self.searchtext2 = QtGui.QLabel(self.searchWidget)
        self.searchtext2.setGeometry(QtCore.QRect(818, 20, 44, 15))
        self.searchtext2.setText(_fromUtf8(""))
        self.searchtext2.setObjectName(_fromUtf8("searchtext2"))
        self.taskWidget = QtGui.QWidget(self.rightWidget)
        self.taskWidget.setGeometry(QtCore.QRect(0, 0, 320, 600))
        self.taskWidget.setObjectName(_fromUtf8("taskWidget"))
        self.taskListWidget = QtGui.QListWidget(self.taskWidget)
        self.taskListWidget.setGeometry(QtCore.QRect(10, 10, 300, 680))
        self.taskListWidget.setObjectName(_fromUtf8("taskListWidget"))
        self.upWidget = QtGui.QWidget(self.rightWidget)
        self.upWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.upWidget.setObjectName(_fromUtf8("upWidget"))
        self.upline = QtGui.QLabel(self.upWidget)
        self.upline.setGeometry(QtCore.QRect(0, 44, 860, 1))
        self.upline.setText(_fromUtf8(""))
        self.upline.setObjectName(_fromUtf8("upline"))
        self.upcount = QtGui.QLabel(self.upWidget)
        self.upcount.setGeometry(QtCore.QRect(777, 20, 50, 15))
        self.upcount.setText(_fromUtf8(""))
        self.upcount.setObjectName(_fromUtf8("upcount"))
        self.uptext1 = QtGui.QLabel(self.upWidget)
        self.uptext1.setGeometry(QtCore.QRect(750, 20, 50, 15))
        self.uptext1.setText(_fromUtf8(""))
        self.uptext1.setObjectName(_fromUtf8("uptext1"))
        self.uptext2 = QtGui.QLabel(self.upWidget)
        self.uptext2.setGeometry(QtCore.QRect(818, 20, 44, 15))
        self.uptext2.setText(_fromUtf8(""))
        self.uptext2.setObjectName(_fromUtf8("uptext2"))
        self.headerWidget = QtGui.QWidget(self.rightWidget)
        self.headerWidget.setGeometry(QtCore.QRect(20, 0, 860, 36))
        self.headerWidget.setObjectName(_fromUtf8("headerWidget"))
        self.btnClose = QtGui.QPushButton(self.headerWidget)
        self.btnClose.setGeometry(QtCore.QRect(0, 0, 28, 36))
        self.btnClose.setText(_fromUtf8(""))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnMin = QtGui.QPushButton(self.headerWidget)
        self.btnMin.setGeometry(QtCore.QRect(28, 0, 28, 36))
        self.btnMin.setText(_fromUtf8(""))
        self.btnMin.setObjectName(_fromUtf8("btnMin"))
        self.btnConf = QtGui.QPushButton(self.headerWidget)
        self.btnConf.setGeometry(QtCore.QRect(84, 0, 28, 36))
        self.btnConf.setText(_fromUtf8(""))
        self.btnConf.setObjectName(_fromUtf8("btnConf"))
        self.firstFocus = QtGui.QLineEdit(self.headerWidget)
        self.firstFocus.setGeometry(QtCore.QRect(2000, 2000, 10, 10))
        self.firstFocus.setObjectName(_fromUtf8("firstFocus"))
        self.leSearch = QtGui.QLineEdit(self.headerWidget)
        self.leSearch.setGeometry(QtCore.QRect(600, 12, 260, 24))
        self.leSearch.setObjectName(_fromUtf8("leSearch"))
        self.lebg = QtGui.QLabel(self.headerWidget)
        self.lebg.setGeometry(QtCore.QRect(838, 16, 16, 16))
        self.lebg.setText(_fromUtf8(""))
        self.lebg.setObjectName(_fromUtf8("lebg"))
        self.btnMaxNormal = QtGui.QPushButton(self.headerWidget)
        self.btnMaxNormal.setGeometry(QtCore.QRect(56, 0, 28, 36))
        self.btnMaxNormal.setText(_fromUtf8(""))
        self.btnMaxNormal.setObjectName(_fromUtf8("btnMaxNormal"))
        self.winpageWidget = QtGui.QWidget(self.rightWidget)
        self.winpageWidget.setGeometry(QtCore.QRect(20, 36, 880, 572))
        self.winpageWidget.setObjectName(_fromUtf8("winpageWidget"))
        self.wincountlabel = QtGui.QLabel(self.winpageWidget)
        self.wincountlabel.setGeometry(QtCore.QRect(777, 20, 50, 15))
        self.wincountlabel.setText(_fromUtf8(""))
        self.wincountlabel.setObjectName(_fromUtf8("wincountlabel"))
        self.winlabel1 = QtGui.QLabel(self.winpageWidget)
        self.winlabel1.setGeometry(QtCore.QRect(750, 20, 50, 15))
        self.winlabel1.setText(_fromUtf8(""))
        self.winlabel1.setObjectName(_fromUtf8("winlabel1"))
        self.wintitle = QtGui.QLabel(self.winpageWidget)
        self.wintitle.setGeometry(QtCore.QRect(0, 26, 301, 15))
        self.wintitle.setText(_fromUtf8(""))
        self.wintitle.setObjectName(_fromUtf8("wintitle"))
        self.winlabel2 = QtGui.QLabel(self.winpageWidget)
        self.winlabel2.setGeometry(QtCore.QRect(818, 20, 44, 15))
        self.winlabel2.setText(_fromUtf8(""))
        self.winlabel2.setObjectName(_fromUtf8("winlabel2"))
        self.winline = QtGui.QLabel(self.winpageWidget)
        self.winline.setGeometry(QtCore.QRect(0, 44, 860, 1))
        self.winline.setText(_fromUtf8(""))
        self.winline.setObjectName(_fromUtf8("winline"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))

