# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Apr 18 15:42:54 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(815, 587)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.leftWidget = QtGui.QWidget(self.centralwidget)
        self.leftWidget.setGeometry(QtCore.QRect(0, 82, 152, 505))
        self.leftWidget.setObjectName(_fromUtf8("leftWidget"))
        self.categoryView = QtGui.QListWidget(self.leftWidget)
        self.categoryView.setGeometry(QtCore.QRect(0, 70, 152, 435))
        self.categoryView.setObjectName(_fromUtf8("categoryView"))
        self.userWidget = QtGui.QWidget(self.leftWidget)
        self.userWidget.setGeometry(QtCore.QRect(0, 0, 152, 70))
        self.userWidget.setObjectName(_fromUtf8("userWidget"))
        self.userLabel = QtGui.QLabel(self.userWidget)
        self.userLabel.setGeometry(QtCore.QRect(20, 12, 46, 46))
        self.userLabel.setText(_fromUtf8(""))
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.userName = QtGui.QLabel(self.userWidget)
        self.userName.setGeometry(QtCore.QRect(72, 18, 80, 18))
        self.userName.setText(_fromUtf8(""))
        self.userName.setObjectName(_fromUtf8("userName"))
        self.userLv = QtGui.QLabel(self.userWidget)
        self.userLv.setGeometry(QtCore.QRect(72, 35, 80, 18))
        self.userLv.setText(_fromUtf8(""))
        self.userLv.setObjectName(_fromUtf8("userLv"))
        self.homepageWidget = QtGui.QWidget(self.centralwidget)
        self.homepageWidget.setGeometry(QtCore.QRect(152, 82, 663, 479))
        self.homepageWidget.setObjectName(_fromUtf8("homepageWidget"))
        self.recommendWidget = QtGui.QWidget(self.homepageWidget)
        self.recommendWidget.setGeometry(QtCore.QRect(0, 214, 529, 265))
        self.recommendWidget.setObjectName(_fromUtf8("recommendWidget"))
        self.rankWidget = QtGui.QWidget(self.homepageWidget)
        self.rankWidget.setGeometry(QtCore.QRect(530, 214, 133, 265))
        self.rankWidget.setObjectName(_fromUtf8("rankWidget"))
        self.rankLogo = QtGui.QLabel(self.rankWidget)
        self.rankLogo.setGeometry(QtCore.QRect(8, 10, 16, 16))
        self.rankLogo.setText(_fromUtf8(""))
        self.rankLogo.setObjectName(_fromUtf8("rankLogo"))
        self.rankText = QtGui.QLabel(self.rankWidget)
        self.rankText.setGeometry(QtCore.QRect(27, 11, 45, 16))
        self.rankText.setObjectName(_fromUtf8("rankText"))
        self.btnDay = QtGui.QPushButton(self.rankWidget)
        self.btnDay.setGeometry(QtCore.QRect(74, 10, 14, 15))
        self.btnDay.setText(_fromUtf8(""))
        self.btnDay.setObjectName(_fromUtf8("btnDay"))
        self.btnWeek = QtGui.QPushButton(self.rankWidget)
        self.btnWeek.setGeometry(QtCore.QRect(92, 10, 14, 15))
        self.btnWeek.setText(_fromUtf8(""))
        self.btnWeek.setObjectName(_fromUtf8("btnWeek"))
        self.btnMonth = QtGui.QPushButton(self.rankWidget)
        self.btnMonth.setGeometry(QtCore.QRect(110, 10, 14, 15))
        self.btnMonth.setText(_fromUtf8(""))
        self.btnMonth.setObjectName(_fromUtf8("btnMonth"))
        self.btnDownTimes = QtGui.QPushButton(self.rankWidget)
        self.btnDownTimes.setGeometry(QtCore.QRect(3, 34, 65, 28))
        self.btnDownTimes.setObjectName(_fromUtf8("btnDownTimes"))
        self.btnGrade = QtGui.QPushButton(self.rankWidget)
        self.btnGrade.setGeometry(QtCore.QRect(66, 34, 65, 28))
        self.btnGrade.setObjectName(_fromUtf8("btnGrade"))
        self.rankView = QtGui.QListWidget(self.rankWidget)
        self.rankView.setGeometry(QtCore.QRect(0, 62, 133, 203))
        self.rankView.setObjectName(_fromUtf8("rankView"))
        self.vline1 = QtGui.QLabel(self.homepageWidget)
        self.vline1.setGeometry(QtCore.QRect(529, 214, 1, 265))
        self.vline1.setText(_fromUtf8(""))
        self.vline1.setObjectName(_fromUtf8("vline1"))
        self.bottomWidget = QtGui.QWidget(self.centralwidget)
        self.bottomWidget.setGeometry(QtCore.QRect(152, 561, 663, 26))
        self.bottomWidget.setObjectName(_fromUtf8("bottomWidget"))
        self.bottomImg = QtGui.QLabel(self.bottomWidget)
        self.bottomImg.setGeometry(QtCore.QRect(438, 4, 18, 18))
        self.bottomImg.setText(_fromUtf8(""))
        self.bottomImg.setObjectName(_fromUtf8("bottomImg"))
        self.bottomText1 = QtGui.QLabel(self.bottomWidget)
        self.bottomText1.setGeometry(QtCore.QRect(463, 3, 140, 19))
        self.bottomText1.setText(_fromUtf8(""))
        self.bottomText1.setObjectName(_fromUtf8("bottomText1"))
        self.bottomText2 = QtGui.QLabel(self.bottomWidget)
        self.bottomText2.setGeometry(QtCore.QRect(608, 3, 50, 19))
        self.bottomText2.setText(_fromUtf8(""))
        self.bottomText2.setObjectName(_fromUtf8("bottomText2"))
        self.upWidget = QtGui.QWidget(self.centralwidget)
        self.upWidget.setGeometry(QtCore.QRect(152, 82, 663, 479))
        self.upWidget.setObjectName(_fromUtf8("upWidget"))
        self.upListWidget = QtGui.QListWidget(self.upWidget)
        self.upListWidget.setGeometry(QtCore.QRect(0, 79, 663, 400))
        self.upListWidget.setObjectName(_fromUtf8("upListWidget"))
        self.upHeader = QtGui.QLabel(self.upWidget)
        self.upHeader.setGeometry(QtCore.QRect(0, 55, 663, 24))
        self.upHeader.setText(_fromUtf8(""))
        self.upHeader.setObjectName(_fromUtf8("upHeader"))
        self.upMSGBar = QtGui.QLabel(self.upWidget)
        self.upMSGBar.setGeometry(QtCore.QRect(0, 0, 663, 55))
        self.upMSGBar.setText(_fromUtf8(""))
        self.upMSGBar.setObjectName(_fromUtf8("upMSGBar"))
        self.unWidget = QtGui.QWidget(self.centralwidget)
        self.unWidget.setGeometry(QtCore.QRect(152, 82, 663, 479))
        self.unWidget.setObjectName(_fromUtf8("unWidget"))
        self.unListWidget = QtGui.QListWidget(self.unWidget)
        self.unListWidget.setGeometry(QtCore.QRect(0, 79, 663, 400))
        self.unListWidget.setObjectName(_fromUtf8("unListWidget"))
        self.unHeader = QtGui.QLabel(self.unWidget)
        self.unHeader.setGeometry(QtCore.QRect(0, 55, 663, 24))
        self.unHeader.setText(_fromUtf8(""))
        self.unHeader.setObjectName(_fromUtf8("unHeader"))
        self.unMSGBar = QtGui.QLabel(self.unWidget)
        self.unMSGBar.setGeometry(QtCore.QRect(0, 0, 663, 55))
        self.unMSGBar.setText(_fromUtf8(""))
        self.unMSGBar.setObjectName(_fromUtf8("unMSGBar"))
        self.allsWidget = QtGui.QWidget(self.centralwidget)
        self.allsWidget.setGeometry(QtCore.QRect(152, 82, 663, 479))
        self.allsWidget.setObjectName(_fromUtf8("allsWidget"))
        self.allsListWidget = QtGui.QListWidget(self.allsWidget)
        self.allsListWidget.setGeometry(QtCore.QRect(0, 79, 663, 400))
        self.allsListWidget.setObjectName(_fromUtf8("allsListWidget"))
        self.allsHeader = QtGui.QLabel(self.allsWidget)
        self.allsHeader.setGeometry(QtCore.QRect(0, 55, 663, 24))
        self.allsHeader.setText(_fromUtf8(""))
        self.allsHeader.setObjectName(_fromUtf8("allsHeader"))
        self.allsMSGBar = QtGui.QLabel(self.allsWidget)
        self.allsMSGBar.setGeometry(QtCore.QRect(0, 0, 663, 55))
        self.allsMSGBar.setText(_fromUtf8(""))
        self.allsMSGBar.setObjectName(_fromUtf8("allsMSGBar"))
        self.headerWidget = QtGui.QWidget(self.centralwidget)
        self.headerWidget.setGeometry(QtCore.QRect(0, 0, 815, 82))
        self.headerWidget.setObjectName(_fromUtf8("headerWidget"))
        self.btnBack = QtGui.QPushButton(self.headerWidget)
        self.btnBack.setGeometry(QtCore.QRect(33, 31, 33, 31))
        self.btnBack.setText(_fromUtf8(""))
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        self.btnNext = QtGui.QPushButton(self.headerWidget)
        self.btnNext.setGeometry(QtCore.QRect(81, 31, 33, 31))
        self.btnNext.setText(_fromUtf8(""))
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.btnHomepage = QtGui.QPushButton(self.headerWidget)
        self.btnHomepage.setGeometry(QtCore.QRect(151, 0, 103, 83))
        self.btnHomepage.setText(_fromUtf8(""))
        self.btnHomepage.setObjectName(_fromUtf8("btnHomepage"))
        self.btnUp = QtGui.QPushButton(self.headerWidget)
        self.btnUp.setGeometry(QtCore.QRect(253, 0, 103, 83))
        self.btnUp.setText(_fromUtf8(""))
        self.btnUp.setObjectName(_fromUtf8("btnUp"))
        self.btnUn = QtGui.QPushButton(self.headerWidget)
        self.btnUn.setGeometry(QtCore.QRect(355, 0, 103, 83))
        self.btnUn.setText(_fromUtf8(""))
        self.btnUn.setObjectName(_fromUtf8("btnUn"))
        self.logoImg = QtGui.QLabel(self.headerWidget)
        self.logoImg.setGeometry(QtCore.QRect(659, 18, 127, 44))
        self.logoImg.setText(_fromUtf8(""))
        self.logoImg.setObjectName(_fromUtf8("logoImg"))
        self.btnTask = QtGui.QPushButton(self.headerWidget)
        self.btnTask.setGeometry(QtCore.QRect(457, 0, 103, 83))
        self.btnTask.setText(_fromUtf8(""))
        self.btnTask.setObjectName(_fromUtf8("btnTask"))
        self.btnClose = QtGui.QPushButton(self.headerWidget)
        self.btnClose.setGeometry(QtCore.QRect(5, 5, 15, 15))
        self.btnClose.setText(_fromUtf8(""))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnMin = QtGui.QPushButton(self.headerWidget)
        self.btnMin.setGeometry(QtCore.QRect(27, 5, 15, 15))
        self.btnMin.setText(_fromUtf8(""))
        self.btnMin.setObjectName(_fromUtf8("btnMin"))
        self.btnConf = QtGui.QPushButton(self.headerWidget)
        self.btnConf.setGeometry(QtCore.QRect(50, 5, 15, 15))
        self.btnConf.setText(_fromUtf8(""))
        self.btnConf.setObjectName(_fromUtf8("btnConf"))
        self.searchWidget = QtGui.QWidget(self.centralwidget)
        self.searchWidget.setGeometry(QtCore.QRect(152, 82, 663, 479))
        self.searchWidget.setObjectName(_fromUtf8("searchWidget"))
        self.searchListWidget = QtGui.QListWidget(self.searchWidget)
        self.searchListWidget.setGeometry(QtCore.QRect(0, 79, 663, 400))
        self.searchListWidget.setObjectName(_fromUtf8("searchListWidget"))
        self.searchHeader = QtGui.QLabel(self.searchWidget)
        self.searchHeader.setGeometry(QtCore.QRect(0, 55, 663, 24))
        self.searchHeader.setText(_fromUtf8(""))
        self.searchHeader.setObjectName(_fromUtf8("searchHeader"))
        self.searchMSGBar = QtGui.QLabel(self.searchWidget)
        self.searchMSGBar.setGeometry(QtCore.QRect(0, 0, 663, 55))
        self.searchMSGBar.setText(_fromUtf8(""))
        self.searchMSGBar.setObjectName(_fromUtf8("searchMSGBar"))
        self.taskWidget = QtGui.QWidget(self.centralwidget)
        self.taskWidget.setGeometry(QtCore.QRect(0, 82, 815, 479))
        self.taskWidget.setObjectName(_fromUtf8("taskWidget"))
        self.taskHeader = QtGui.QLabel(self.taskWidget)
        self.taskHeader.setGeometry(QtCore.QRect(0, 55, 815, 24))
        self.taskHeader.setText(_fromUtf8(""))
        self.taskHeader.setObjectName(_fromUtf8("taskHeader"))
        self.taskMSGBar = QtGui.QLabel(self.taskWidget)
        self.taskMSGBar.setGeometry(QtCore.QRect(0, 0, 815, 55))
        self.taskMSGBar.setText(_fromUtf8(""))
        self.taskMSGBar.setObjectName(_fromUtf8("taskMSGBar"))
        self.taskListWidget = QtGui.QListWidget(self.taskWidget)
        self.taskListWidget.setGeometry(QtCore.QRect(0, 79, 815, 400))
        self.taskListWidget.setObjectName(_fromUtf8("taskListWidget"))
        self.searchBG = QtGui.QWidget(self.centralwidget)
        self.searchBG.setGeometry(QtCore.QRect(152, 82, 663, 33))
        self.searchBG.setObjectName(_fromUtf8("searchBG"))
        self.leSearch = QtGui.QLineEdit(self.searchBG)
        self.leSearch.setGeometry(QtCore.QRect(495, 7, 131, 18))
        self.leSearch.setObjectName(_fromUtf8("leSearch"))
        self.lebg = QtGui.QLabel(self.searchBG)
        self.lebg.setGeometry(QtCore.QRect(478, 7, 157, 18))
        self.lebg.setText(_fromUtf8(""))
        self.lebg.setObjectName(_fromUtf8("lebg"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.rankText.setText(_translate("MainWindow", "排行榜", None))
        self.btnDownTimes.setText(_translate("MainWindow", "下载排行", None))
        self.btnGrade.setText(_translate("MainWindow", "评分排行", None))

